qt_add_library(MarvisKit STATIC)

qt_add_qml_module(MarvisKit
    URI MarvisKit
    VERSION 1.0
    QML_FILES
        MarvisPalette.qml
        MvAccordion.qml
        MvAvatar.qml
        MvAvatarGroup.qml
        MvBadge.qml
        MvBreadcrumb.qml
        MvButton.qml
        MvCard.qml
        MvCheckbox.qml
        MvChip.qml
        MvCalendar.qml
        MvColorSwatch.qml
        MvComboBox.qml
        MvCommandItem.qml
        MvDial.qml
        MvDialog.qml
        MvDivider.qml
        MvDrawer.qml
        MvFileCard.qml
        MvFrame.qml
        MvGroupBox.qml
        MvIconButton.qml
        MvListItem.qml
        MvMenuButton.qml
        MvMessageBubble.qml
        MvNavItem.qml
        MvPanel.qml
        MvPagination.qml
        MvPopover.qml
        MvProgressBar.qml
        MvPageIndicator.qml
        MvRadio.qml
        MvRangeSlider.qml
        MvSearchField.qml
        MvSegmentedControl.qml
        MvShortcut.qml
        MvSlider.qml
        MvSpinner.qml
        MvScrollBar.qml
        MvStepper.qml
        MvSplitView.qml
        MvStatusDot.qml
        MvTabBar.qml
        MvTable.qml
        MvTextArea.qml
        MvTextField.qml
        MvToast.qml
        MvToolTip.qml
        MvToggle.qml
        MvToolbar.qml
        MvTreeItem.qml
        MvNotification.qml
)

target_link_libraries(MarvisKit
    PRIVATE
        Qt6::Quick
        Qt6::QuickControls2
)
